version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes_from:
      - datastore

  web:
    build:
      context: .
    # command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/justinlab
    volumes_from:
      - datastore
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local
